apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiss
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-swiss
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-swiss
    spec:
      containers:
      - image: rootsh/infracore-swiss-knife
        imagePullPolicy: IfNotPresent
        name: swiss
        securityContext:
          runAsUser: 0
          allowPrivilegeEscalation: true
          privileged: true
        stdin: true
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: {}
      serviceAccountName: {}

